name: Lint PR for app_theme.json

on:
  pull_request:
    paths:
      - "app_theme.json"

jobs:
  lint-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # Only fetch the current PR state

      - name: Check for '#' character in app_theme.json
        id: check_hash
        run: |
          if grep -q "#" app_theme.json; then
            echo "Hash (#) character found in app_theme.json."
          else
            echo "No hash (#) character found in app_theme.json."
            exit 1

      - name: Lint Passed
        if: success()
        run: echo "Lint passed. PR is valid."

      - name: Lint Failed
        if: failure()
        run: echo "Lint failed. No hash (#) character found in app_theme.json."
